os: osx
osx_image: xcode12
language: swift
script: xcodebuild clean build test -project DebitTracker2.xcodeproj -scheme DebitTracker2 -sdk iphonesimulator -destination “platform=iOS Simulator,OS=14.0,name=iPhone 8” ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
