os: osx
osx_image: xcode12
language: swift
script: xcodebuild clean build test -project Travis_CIDemo/Travis_CIDemo.xcodeproj -scheme Travis_CIDemo -sdk iphonesimulator -destination “platform=iOS Simulator,OS=12.1,name=iPhone 6” ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO
